# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Cadre Demo
email: smlee.981@gmail.com
description: The best static blogging theme money can buy. 
url: https://stephenlee.info 
baseurl: /jekyll-theme-cadre

# Cadre settins
about: Cadre is a responsive, modern Jekyll theme for bloggers. This theme is designed to come with good defaults including an archive and categories page "out of the box". 
# about_img: "/assets/images/SparklingCorrelation-full.png"
# navbar_img: "/assets/images/SparklingCorrelation.png"
# favicon_img: "/assets/images/favicon.png"
paginate: 3
exclude_powered_by: false

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme

remote_theme: slee981/jekyll-theme-cadre

include:
  - _pages

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - scripts/

sass:
  sass_dir: _sass
  style: :compressed

